### Option: StartAPMCollectors
#	Number of pre-forked APM collector instances (0-1).
StartAPMCollectors=${ZBX_STARTAPMCOLLECTORS}

### Option: APMListenIP
#	IP addresses that the APM collector should listen on.
APMListenIP=${ZBX_APMLISTENIP}

### Option: APMListenPort
#	Listen port for APM collector (1024-32767).
APMListenPort=${ZBX_APMLISTENPORT}

### Option: APMTLSCAFile
#	Top-level CA(s) certificates for peer certificate verification by APM collector.
APMTLSCAFile=${ZBX_APMTLSCAFILE}

### Option: APMTLSCertFile
#	APM collector certificate or certificate chain.
APMTLSCertFile=${ZBX_APMTLSCERTFILE}

### Option: APMTLSKeyFile
#	APM collector private key.
APMTLSKeyFile=${ZBX_APMTLSKEYFILE}
